# Site settings
title: Ralph Warrand - Game Developer Portfolio
email: ralphwarrand@gmail.com
description: >-
  Portfolio showcasing my journey as a Creative Media and Game Technologies student
  at Breda University of Applied Sciences and beyond.
baseurl: "/portfolio"
url: "https://ralphwarrand.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

